[package]
authors = ["Kai Schmidt <kai.schmidt@constructioninnovations.com>"]
edition = "2018"
name = "before"
version = "0.1.0"

[dependencies]
serde.features = ["derive"]
serde.version = "1"

[dev-dependencies]
serde_json = "1"
